import re

file_path = 'h:/Quizonator/Rozszerzenie 2.0/frontend/src/app/pages/mobile-install.component.ts'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace the mockMenuCopy with get t() 
t_getter = r'''  get t() {
    const texts: Record<string, any> = {
      en: {
        eyebrow: 'Mobile Extension',
        title: 'QuizSolver on Your Phone',
        subtitle: 'Solve quizzes and tests directly from your smartphone. Choose your operating system below for step-by-step instructions.',
        trustFree: '100% free',
        trustTime: '~3 minutes',
        trustRoot: 'No root needed',
        reqKiwi: 'Requires Kiwi Browser',
        step4TitleSummary: 'Android Installation in 4 Steps',
        kiwiDesc: 'Standard Chrome on Android blocks extensions. The fix? Kiwi Browser — a fast browser built on Chromium that supports full Chrome Web Store extensions.',
        getKiwi: 'Get Kiwi Browser',
        copied: 'Copied Link!',
        copyLink: 'Copy Extension URL',
        copyLinkShort: 'Copy link',
        copiedShort: '✓ Copied',
        chromeAndroid: 'Android Chrome',
        noExt: 'No extension support',
        noStore: 'No Web Store access',
        vs: 'VS',
        fullStore: 'Full Chrome Web Store support',
        sameEngine: 'Same engine as Chrome — fast & stable',
        step1: 'Step 1',
        step1Title: 'Install Kiwi Browser from Google Play',
        step1Desc: 'Open Google Play on your phone and install the free Kiwi Browser application.',
        install: 'Install',
        step2: 'Step 2',
        step2Title: 'Open Chrome Web Store in Kiwi',
        step2Desc: 'Launch Kiwi Browser on your device, paste the extension URL into the address bar and tap "Add to Chrome".',
        addToChrome: 'Add to Chrome',
        openStore: 'Open Web Store',
        step3: 'Step 3',
        step3Title: 'Open Extension from the 3-Dots Menu',
        step3Desc: 'Tap the three dots (⋮) in the top-right corner of Kiwi and scroll to the bottom. Tap QuizSolver and log in with your email to access your credits.',
        step4: 'Ready',
        step4Title: 'Solve Quizzes Directly on Mobile',
        step4Desc: 'Open any quiz in Kiwi. Open Kiwi menu -> QuizSolver -> tap "Solve current page" or use FocusScan.',
        worksSame: 'Works exactly like the desktop version',
        worksSameDesc: 'Automatic detection, hint mode, FocusScan and study history are fully supported.',
        tryDemo: 'Try Free Demo',
        feat1Title: 'Auto question detection',
        feat1Desc: 'Finds quiz questions on the page automatically',
        feat2Title: 'FocusScan',
        feat2Desc: 'Scan and solve a selected part of the screen',
        feat3Title: 'Hint mode',
        feat3Desc: 'Gentle nudges instead of full answers',
        feat4Title: 'Question history',
        feat4Desc: 'Everything saved for exam revision',
        iosTitle: 'Video Tutorial for iOS (iPhone / iPad)',
        iosDesc: 'Watch this 40-second video demonstrating the setup process on Apple devices.',
        iosBtn: 'Open in YouTube app',
        newTab: 'New tab',
        settings: 'Settings',
        active: 'ACTIVE',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      pl: {
        eyebrow: 'Aplikacja Mobilna',
        title: 'QuizSolver na Twoim Telefonie',
        subtitle: 'Rozwiązuj testy, kolokwia i quizy bezpośrednio ze smartfona. Wybierz swój system, aby zobaczyć instrukcję instalacji krok po kroku.',
        trustFree: '100% za darmo',
        trustTime: '~3 minuty',
        trustRoot: 'Bez roota',
        reqKiwi: 'Wymaga Kiwi Browser',
        step4TitleSummary: 'Instalacja na Androidzie w 4 krokach',
        kiwiDesc: 'Standardowy mobilny Chrome nie pozwala instalować rozszerzeń. Rozwiązanie? Kiwi Browser — lekka przeglądarka na tym samym silniku Chromium, która obsługuje wtyczki z Chrome Web Store.',
        getKiwi: 'Pobierz Kiwi Browser',
        copied: 'Skopiowano link!',
        copyLink: 'Skopiuj link wtyczki',
        copyLinkShort: 'Kopiuj link',
        copiedShort: '✓ Skopiowano',
        chromeAndroid: 'Chrome na Androidzie',
        noExt: 'Nie obsługuje rozszerzeń',
        noStore: 'Brak dostępu do Web Store',
        vs: 'KONTRA',
        fullStore: 'Pełne wsparcie Chrome Web Store',
        sameEngine: 'Ten sam silnik co Chrome — szybka i stabilna',
        step1: 'Krok 1',
        step1Title: 'Pobierz Kiwi Browser z Google Play',
        step1Desc: 'Wejdź do sklepu Google Play na swoim telefonie i zainstaluj darmową przeglądarkę Kiwi Browser.',
        install: 'Zainstaluj',
        step2: 'Krok 2',
        step2Title: 'Otwórz Chrome Web Store wewnątrz Kiwi',
        step2Desc: 'Uruchom Kiwi Browser na telefonie, wklej link do paska adresu i kliknij niebieski przycisk „Dodaj do Chrome".',
        addToChrome: 'Dodaj do Chrome',
        openStore: 'Otwórz stronę wtyczki',
        step3: 'Krok 3',
        step3Title: 'Włącz wtyczkę z menu Kiwi (3 kropki)',
        step3Desc: 'Kliknij menu w prawym górnym rogu Kiwi (trzy kropki ⋮), zjedź na sam dół listy i stuknij QuizSolver. Zaloguj się tym samym adresem e-mail, aby mieć dostęp do swoich kredytów.',
        step4: 'Gotowe',
        step4Title: 'Rozwiązuj testy bezpośrednio na telefonie',
        step4Desc: 'Otwórz dowolny test w Kiwi. Otwórz menu Kiwi -> QuizSolver -> kliknij „Rozwiąż obecną stronę" lub użyj FocusScan.',
        worksSame: 'Wszystko działa dokładnie tak jak na komputerze',
        worksSameDesc: 'Wykrywanie pytań, tryb podpowiedzi, FocusScan i historia pytań są w 100% dostępne.',
        tryDemo: 'Przetestuj na darmowym Demo',
        feat1Title: 'Auto-wykrywanie pytań',
        feat1Desc: 'Wtyczka sama znajduje pytania na stronie',
        feat2Title: 'FocusScan',
        feat2Desc: 'Skanuj i rozwiązuj wybrany fragment ekranu',
        feat3Title: 'Tryb podpowiedzi',
        feat3Desc: 'Wskazówki zamiast gotowych odpowiedzi',
        feat4Title: 'Historia pytań',
        feat4Desc: 'Wszystko zapisane do nauki przed egzaminem',
        iosTitle: 'Wideo Poradnik dla iOS (iPhone / iPad)',
        iosDesc: 'Zobacz 40-sekundowe nagranie pokazujące instalację rozszerzenia na urządzeniach Apple.',
        iosBtn: 'Otwórz na YouTube',
        newTab: 'Nowa karta',
        settings: 'Ustawienia',
        active: 'AKTYWNY',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      de: {
        eyebrow: 'Mobile Erweiterung',
        title: 'QuizSolver auf Ihrem Handy',
        subtitle: 'Lösen Sie Tests und Quizze direkt von Ihrem Smartphone aus. Wählen Sie unten Ihr Betriebssystem für eine Schritt-für-Schritt-Anleitung.',
        trustFree: '100% kostenlos',
        trustTime: '~3 Minuten',
        trustRoot: 'Kein Root nötig',
        reqKiwi: 'Benötigt Kiwi Browser',
        step4TitleSummary: 'Android-Installation in 4 Schritten',
        kiwiDesc: 'Standard Chrome auf Android blockiert Erweiterungen. Die Lösung? Kiwi Browser — ein schneller Browser basierend auf Chromium, der alle Chrome Web Store-Erweiterungen unterstützt.',
        getKiwi: 'Kiwi Browser herunterladen',
        copied: 'Link kopiert!',
        copyLink: 'Erweiterungs-Link kopieren',
        copyLinkShort: 'Link kopieren',
        copiedShort: '✓ Kopiert',
        chromeAndroid: 'Android Chrome',
        noExt: 'Keine Erweiterungen unterstützt',
        noStore: 'Kein Web Store-Zugriff',
        vs: 'VS',
        fullStore: 'Volle Chrome Web Store-Unterstützung',
        sameEngine: 'Gleiche Engine wie Chrome — schnell & stabil',
        step1: 'Schritt 1',
        step1Title: 'Kiwi Browser bei Google Play installieren',
        step1Desc: 'Öffnen Sie Google Play auf Ihrem Telefon und installieren Sie die kostenlose Kiwi Browser App.',
        install: 'Installieren',
        step2: 'Schritt 2',
        step2Title: 'Chrome Web Store im Kiwi öffnen',
        step2Desc: 'Starten Sie den Kiwi Browser, fügen Sie die Erweiterungs-URL in die Adressleiste ein und tippen Sie auf "Hinzufügen".',
        addToChrome: 'Hinzufügen',
        openStore: 'Web Store öffnen',
        step3: 'Schritt 3',
        step3Title: 'Erweiterung über das 3-Punkte-Menü öffnen',
        step3Desc: 'Tippen Sie auf die drei Punkte (⋮) oben rechts im Kiwi und scrollen Sie nach unten. Tippen Sie auf QuizSolver und melden Sie sich an.',
        step4: 'Fertig',
        step4Title: 'Quizze direkt auf dem Handy lösen',
        step4Desc: 'Öffnen Sie ein beliebiges Quiz in Kiwi. Öffnen Sie das Kiwi-Menü -> QuizSolver -> tippen Sie auf "Aktuelle Seite lösen".',
        worksSame: 'Funktioniert genau wie die Desktop-Version',
        worksSameDesc: 'Automatische Erkennung, Hinweismodus, FocusScan und Lernhistorie werden voll unterstützt.',
        tryDemo: 'Kostenlose Demo testen',
        feat1Title: 'Automatische Fragenerkennung',
        feat1Desc: 'Findet Quizfragen automatisch auf der Seite',
        feat2Title: 'FocusScan',
        feat2Desc: 'Scannen und lösen Sie einen Teil des Bildschirms',
        feat3Title: 'Hinweis-Modus',
        feat3Desc: 'Sanfte Hinweise statt voller Antworten',
        feat4Title: 'Fragenverlauf',
        feat4Desc: 'Alles für die Prüfungswiederholung gespeichert',
        iosTitle: 'Video-Tutorial für iOS (iPhone / iPad)',
        iosDesc: 'Sehen Sie sich dieses 40-sekündige Video an, das die Einrichtung auf Apple-Geräten zeigt.',
        iosBtn: 'In YouTube-App öffnen',
        newTab: 'Neuer Tab',
        settings: 'Einstellungen',
        active: 'AKTIV',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      es: {
        eyebrow: 'Extensión móvil',
        title: 'QuizSolver en tu teléfono',
        subtitle: 'Resuelve cuestionarios y pruebas directamente desde tu teléfono inteligente. Elige tu sistema operativo para las instrucciones.',
        trustFree: '100% gratis',
        trustTime: '~3 minutos',
        trustRoot: 'Sin root',
        reqKiwi: 'Requiere Kiwi Browser',
        step4TitleSummary: 'Instalación en Android en 4 pasos',
        kiwiDesc: 'Chrome en Android bloquea las extensiones. ¿La solución? Kiwi Browser — un navegador basado en Chromium que admite extensiones del Chrome Web Store.',
        getKiwi: 'Obtener Kiwi Browser',
        copied: '¡Enlace copiado!',
        copyLink: 'Copiar enlace',
        copyLinkShort: 'Copiar enlace',
        copiedShort: '✓ Copiado',
        chromeAndroid: 'Chrome en Android',
        noExt: 'Sin soporte de extensiones',
        noStore: 'Sin acceso a Web Store',
        vs: 'VS',
        fullStore: 'Soporte completo de Web Store',
        sameEngine: 'Mismo motor que Chrome — rápido y estable',
        step1: 'Paso 1',
        step1Title: 'Instalar Kiwi Browser desde Google Play',
        step1Desc: 'Abre Google Play en tu teléfono e instala la aplicación gratuita Kiwi Browser.',
        install: 'Instalar',
        step2: 'Paso 2',
        step2Title: 'Abrir Chrome Web Store en Kiwi',
        step2Desc: 'Inicia Kiwi Browser, pega la URL de la extensión en la barra de direcciones y toca "Añadir a Chrome".',
        addToChrome: 'Añadir',
        openStore: 'Abrir Web Store',
        step3: 'Paso 3',
        step3Title: 'Abrir extensión desde el menú (3 puntos)',
        step3Desc: 'Toca los tres puntos (⋮) en la esquina superior derecha de Kiwi y desplázate hasta abajo. Toca QuizSolver e inicia sesión.',
        step4: 'Listo',
        step4Title: 'Resuelve cuestionarios en el móvil',
        step4Desc: 'Abre cualquier cuestionario en Kiwi. Menú Kiwi -> QuizSolver -> "Resolver página actual".',
        worksSame: 'Funciona exactamente como en PC',
        worksSameDesc: 'Detección automática, modo pistas, FocusScan e historial de estudio.',
        tryDemo: 'Probar demostración',
        feat1Title: 'Detección automática',
        feat1Desc: 'Encuentra las preguntas de la página',
        feat2Title: 'FocusScan',
        feat2Desc: 'Escanea y resuelve una parte de la pantalla',
        feat3Title: 'Modo pistas',
        feat3Desc: 'Sutiles pistas en lugar de respuestas',
        feat4Title: 'Historial de preguntas',
        feat4Desc: 'Todo guardado para el examen',
        iosTitle: 'Tutorial en video para iOS (iPhone / iPad)',
        iosDesc: 'Mira este video de 40 segundos que demuestra el proceso en dispositivos Apple.',
        iosBtn: 'Abrir en YouTube',
        newTab: 'Nueva pestaña',
        settings: 'Configuración',
        active: 'ACTIVO',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      fr: {
        eyebrow: 'Extension Mobile',
        title: 'QuizSolver sur votre téléphone',
        subtitle: 'Résolvez des quiz et des tests depuis votre smartphone. Choisissez votre système d\'exploitation ci-dessous.',
        trustFree: '100% gratuit',
        trustTime: '~3 minutes',
        trustRoot: 'Pas de root',
        reqKiwi: 'Kiwi Browser requis',
        step4TitleSummary: 'Installation Android en 4 étapes',
        kiwiDesc: 'Chrome sur Android bloque les extensions. La solution ? Kiwi Browser — un navigateur basé sur Chromium qui supporte le Chrome Web Store.',
        getKiwi: 'Télécharger Kiwi Browser',
        copied: 'Lien copié !',
        copyLink: 'Copier le lien',
        copyLinkShort: 'Copier le lien',
        copiedShort: '✓ Copié',
        chromeAndroid: 'Chrome Android',
        noExt: 'Pas d\'extensions',
        noStore: 'Pas de Web Store',
        vs: 'VS',
        fullStore: 'Support complet du Web Store',
        sameEngine: 'Même moteur que Chrome — rapide & stable',
        step1: 'Étape 1',
        step1Title: 'Installer Kiwi Browser (Google Play)',
        step1Desc: 'Ouvrez Google Play sur votre téléphone et installez l\'application gratuite Kiwi Browser.',
        install: 'Installer',
        step2: 'Étape 2',
        step2Title: 'Ouvrir le Web Store dans Kiwi',
        step2Desc: 'Lancez Kiwi Browser, collez l\'URL de l\'extension dans la barre d\'adresse et appuyez sur "Ajouter à Chrome".',
        addToChrome: 'Ajouter',
        openStore: 'Ouvrir le Web Store',
        step3: 'Étape 3',
        step3Title: 'Ouvrir l\'extension (Menu ⋮)',
        step3Desc: 'Appuyez sur les trois points (⋮) en haut à droite de Kiwi, descendez tout en bas. Appuyez sur QuizSolver et connectez-vous.',
        step4: 'Prêt',
        step4Title: 'Résolvez des quiz sur mobile',
        step4Desc: 'Ouvrez un quiz dans Kiwi. Menu Kiwi -> QuizSolver -> "Résoudre la page".',
        worksSame: 'Fonctionne comme sur ordinateur',
        worksSameDesc: 'Détection automatique, mode indice, FocusScan et historique de révision.',
        tryDemo: 'Essayer la démo',
        feat1Title: 'Détection automatique',
        feat1Desc: 'Trouve les questions automatiquement',
        feat2Title: 'FocusScan',
        feat2Desc: 'Analysez et résolvez une partie de l\'écran',
        feat3Title: 'Mode indice',
        feat3Desc: 'Des indices au lieu des réponses complètes',
        feat4Title: 'Historique des questions',
        feat4Desc: 'Tout est sauvegardé pour vos révisions',
        iosTitle: 'Tutoriel vidéo pour iOS (iPhone / iPad)',
        iosDesc: 'Regardez cette vidéo de 40 secondes expliquant la configuration sur les appareils Apple.',
        iosBtn: 'Ouvrir dans YouTube',
        newTab: 'Nouvel onglet',
        settings: 'Paramètres',
        active: 'ACTIF',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      it: {
        eyebrow: 'Estensione Mobile',
        title: 'QuizSolver sul tuo telefono',
        subtitle: 'Risolvi quiz e test direttamente dallo smartphone. Scegli il tuo sistema operativo per le istruzioni.',
        trustFree: '100% gratis',
        trustTime: '~3 minuti',
        trustRoot: 'Nessun root',
        reqKiwi: 'Richiede Kiwi Browser',
        step4TitleSummary: 'Installazione Android in 4 passi',
        kiwiDesc: 'Chrome su Android blocca le estensioni. La soluzione? Kiwi Browser — un browser basato su Chromium che supporta il Chrome Web Store.',
        getKiwi: 'Scarica Kiwi Browser',
        copied: 'Link copiato!',
        copyLink: 'Copia link',
        copyLinkShort: 'Copia link',
        copiedShort: '✓ Copiato',
        chromeAndroid: 'Android Chrome',
        noExt: 'Nessuna estensione',
        noStore: 'Nessun Web Store',
        vs: 'VS',
        fullStore: 'Supporto completo Web Store',
        sameEngine: 'Stesso motore di Chrome — veloce',
        step1: 'Passo 1',
        step1Title: 'Installa Kiwi Browser da Google Play',
        step1Desc: 'Apri Google Play sul telefono e installa l\'app gratuita Kiwi Browser.',
        install: 'Installa',
        step2: 'Passo 2',
        step2Title: 'Apri Chrome Web Store in Kiwi',
        step2Desc: 'Avvia Kiwi Browser, incolla l\'URL dell\'estensione e tocca "Aggiungi a Chrome".',
        addToChrome: 'Aggiungi',
        openStore: 'Apri Web Store',
        step3: 'Passo 3',
        step3Title: 'Apri l\'estensione dal menu (⋮)',
        step3Desc: 'Tocca i tre puntini (⋮) in alto a destra su Kiwi e scorri in basso. Tocca QuizSolver e accedi.',
        step4: 'Pronto',
        step4Title: 'Risolvi i quiz sul cellulare',
        step4Desc: 'Apri qualsiasi quiz in Kiwi. Menu Kiwi -> QuizSolver -> tocca "Risolvi pagina".',
        worksSame: 'Funziona esattamente come su PC',
        worksSameDesc: 'Rilevamento automatico, modalità suggerimento, FocusScan e cronologia studio.',
        tryDemo: 'Prova la Demo',
        feat1Title: 'Rilevamento automatico',
        feat1Desc: 'Trova le domande automaticamente',
        feat2Title: 'FocusScan',
        feat2Desc: 'Scansiona e risolvi una parte dello schermo',
        feat3Title: 'Modalità Suggerimento',
        feat3Desc: 'Piccoli aiuti al posto delle risposte',
        feat4Title: 'Cronologia domande',
        feat4Desc: 'Tutto salvato per il ripasso',
        iosTitle: 'Video Tutorial per iOS (iPhone / iPad)',
        iosDesc: 'Guarda questo video di 40 secondi che mostra l\'installazione sui dispositivi Apple.',
        iosBtn: 'Apri in YouTube',
        newTab: 'Nuova scheda',
        settings: 'Impostazioni',
        active: 'ATTIVO',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      },
      uk: {
        eyebrow: 'Мобільне розширення',
        title: 'QuizSolver на вашому телефоні',
        subtitle: 'Вирішуйте тести та вікторини прямо зі смартфона. Виберіть операційну систему нижче.',
        trustFree: '100% безкоштовно',
        trustTime: '~3 хвилини',
        trustRoot: 'Root не потрібен',
        reqKiwi: 'Потрібен Kiwi Browser',
        step4TitleSummary: 'Встановлення на Android за 4 кроки',
        kiwiDesc: 'Стандартний Chrome на Android блокує розширення. Рішення? Kiwi Browser — швидкий браузер, який підтримує Chrome Web Store.',
        getKiwi: 'Завантажити Kiwi Browser',
        copied: 'Посилання скопійовано!',
        copyLink: 'Копіювати посилання',
        copyLinkShort: 'Копіювати',
        copiedShort: '✓ Скопійовано',
        chromeAndroid: 'Android Chrome',
        noExt: 'Немає розширень',
        noStore: 'Немає доступу до Web Store',
        vs: 'ПРОТИ',
        fullStore: 'Повна підтримка Chrome Web Store',
        sameEngine: 'Той самий рушій, що й у Chrome',
        step1: 'Крок 1',
        step1Title: 'Встановіть Kiwi Browser з Google Play',
        step1Desc: 'Відкрийте Google Play на своєму телефоні та встановіть безкоштовний Kiwi Browser.',
        install: 'Встановити',
        step2: 'Крок 2',
        step2Title: 'Відкрийте Chrome Web Store в Kiwi',
        step2Desc: 'Запустіть Kiwi Browser, вставте URL-адресу розширення та натисніть "Додати".',
        addToChrome: 'Додати',
        openStore: 'Відкрити Web Store',
        step3: 'Крок 3',
        step3Title: 'Відкрийте розширення з меню (⋮)',
        step3Desc: 'Натисніть на три крапки (⋮) у верхньому правому куті Kiwi. Натисніть QuizSolver та увійдіть.',
        step4: 'Готово',
        step4Title: 'Вирішуйте тести на мобільному',
        step4Desc: 'Відкрийте будь-який тест у Kiwi. Меню Kiwi -> QuizSolver -> натисніть "Вирішити сторінку".',
        worksSame: 'Працює так само, як і на ПК',
        worksSameDesc: 'Автоматичне виявлення, режим підказок, FocusScan та історія навчання.',
        tryDemo: 'Спробувати демо',
        feat1Title: 'Авто-виявлення питань',
        feat1Desc: 'Знаходить питання на сторінці',
        feat2Title: 'FocusScan',
        feat2Desc: 'Сканує та вирішує частину екрана',
        feat3Title: 'Режим підказок',
        feat3Desc: 'Підказки замість повних відповідей',
        feat4Title: 'Історія питань',
        feat4Desc: 'Все збережено для повторення',
        iosTitle: 'Відео-інструкція для iOS (iPhone / iPad)',
        iosDesc: 'Перегляньте це 40-секундне відео, що демонструє налаштування на пристроях Apple.',
        iosBtn: 'Відкрити в YouTube',
        newTab: 'Нова вкладка',
        settings: 'Налаштування',
        active: 'АКТИВНИЙ',
        qsTitle: 'QuizSolver — AI Quiz Solver'
      }
    };
    return texts[this.locale] || texts['en'];
  }
'''

content = re.sub(r'  get mockMenuCopy\(\) \{[\s\S]*?\}\n', t_getter, content)

# Now substitute all template usage with t.propertyName
replacements = {
    r"\{\{\s*isPl\s*\?\s*'Aplikacja Mobilna'\s*:\s*'Mobile Extension'\s*\}\}": "{{ t.eyebrow }}",
    r"\{\{\s*isPl\s*\?\s*'QuizSolver na Twoim Telefonie'\s*:\s*'QuizSolver on Your Phone'\s*\}\}": "{{ t.title }}",
    r"\{\{\s*isPl\s*\?\s*'Rozwiązuj testy, kolokwia i quizy bezpośrednio ze smartfona\. Wybierz swój system, aby zobaczyć instrukcję instalacji krok po kroku\.'\s*:\s*'Solve quizzes and tests directly from your smartphone\. Choose your operating system below for step-by-step instructions\.'\s*\}\}": "{{ t.subtitle }}",
    r"\{\{\s*isPl\s*\?\s*'100% za darmo'\s*:\s*'100% free'\s*\}\}": "{{ t.trustFree }}",
    r"\{\{\s*isPl\s*\?\s*'~3 minuty'\s*:\s*'~3 minutes'\s*\}\}": "{{ t.trustTime }}",
    r"\{\{\s*isPl\s*\?\s*'Bez roota'\s*:\s*'No root needed'\s*\}\}": "{{ t.trustRoot }}",
    r"\{\{\s*isPl\s*\?\s*'Wymaga Kiwi Browser'\s*:\s*'Requires Kiwi Browser'\s*\}\}": "{{ t.reqKiwi }}",
    r"\{\{\s*isPl\s*\?\s*'Instalacja na Androidzie w 4 krokach'\s*:\s*'Android Installation in 4 Steps'\s*\}\}": "{{ t.step4TitleSummary }}",
    r"\{\{\s*isPl[\s\r\n]*\? 'Standardowy mobilny Chrome nie pozwala instalować rozszerzeń\. Rozwiązanie\? Kiwi Browser — lekka przeglądarka na tym samym silniku Chromium, która obsługuje wtyczki z Chrome Web Store\.'[\s\r\n]*:\s*'Standard Chrome on Android blocks extensions\. The fix\? Kiwi Browser — a fast browser built on Chromium that supports full Chrome Web Store extensions\.'\s*\}\}": "{{ t.kiwiDesc }}",
    r"\{\{\s*isPl\s*\?\s*'Pobierz Kiwi Browser'\s*:\s*'Get Kiwi Browser'\s*\}\}": "{{ t.getKiwi }}",
    r"\{\{\s*copied\(\)\s*\?\s*\(isPl\s*\?\s*'Skopiowano link!'\s*:\s*'Copied Link!'\)\s*:\s*\(isPl\s*\?\s*'Skopiuj link wtyczki'\s*:\s*'Copy Extension URL'\)\s*\}\}": "{{ copied() ? t.copied : t.copyLink }}",
    r"\{\{\s*isPl\s*\?\s*'Chrome na Androidzie'\s*:\s*'Android Chrome'\s*\}\}": "{{ t.chromeAndroid }}",
    r"\{\{\s*isPl\s*\?\s*'Nie obsługuje rozszerzeń'\s*:\s*'No extension support'\s*\}\}": "{{ t.noExt }}",
    r"\{\{\s*isPl\s*\?\s*'Brak dostępu do Web Store'\s*:\s*'No Web Store access'\s*\}\}": "{{ t.noStore }}",
    r"\{\{\s*isPl\s*\?\s*'KONTRA'\s*:\s*'VS'\s*\}\}": "{{ t.vs }}",
    r"\{\{\s*isPl\s*\?\s*'Pełne wsparcie Chrome Web Store'\s*:\s*'Full Chrome Web Store support'\s*\}\}": "{{ t.fullStore }}",
    r"\{\{\s*isPl\s*\?\s*'Ten sam silnik co Chrome — szybka i stabilna'\s*:\s*'Same engine as Chrome — fast & stable'\s*\}\}": "{{ t.sameEngine }}",
    r"\{\{\s*isPl\s*\?\s*'Pobierz Kiwi Browser z Google Play'\s*:\s*'Install Kiwi Browser from Google Play'\s*\}\}": "{{ t.step1Title }}",
    r"\{\{\s*isPl\s*\?\s*'Krok 1'\s*:\s*'Step 1'\s*\}\}": "{{ t.step1 }}",
    r"\{\{\s*isPl[\s\r\n]*\? 'Wejdź do sklepu Google Play na swoim telefonie i zainstaluj darmową przeglądarkę Kiwi Browser\.'[\s\r\n]*:\s*'Open Google Play on your phone and install the free Kiwi Browser application\.'\s*\}\}": "{{ t.step1Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Zainstaluj'\s*:\s*'Install'\s*\}\}": "{{ t.install }}",
    r"\{\{\s*isPl\s*\?\s*'Otwórz Chrome Web Store wewnątrz Kiwi'\s*:\s*'Open Chrome Web Store in Kiwi'\s*\}\}": "{{ t.step2Title }}",
    r"\{\{\s*isPl\s*\?\s*'Krok 2'\s*:\s*'Step 2'\s*\}\}": "{{ t.step2 }}",
    r"\{\{\s*isPl[\s\r\n]*\? 'Uruchom Kiwi Browser na telefonie, wklej link do paska adresu i kliknij niebieski przycisk „Dodaj do Chrome\"\\.'[\s\r\n]*:\s*'Launch Kiwi Browser on your device, paste the extension URL into the address bar and tap \"Add to Chrome\"\\.'\s*\}\}": "{{ t.step2Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Dodaj do Chrome'\s*:\s*'Add to Chrome'\s*\}\}": "{{ t.addToChrome }}",
    r"\{\{\s*copied\(\)\s*\?\s*\(isPl\s*\?\s*'✓ Skopiowano'\s*:\s*'✓ Copied'\)\s*:\s*\(isPl\s*\?\s*'Kopiuj link'\s*:\s*'Copy link'\)\s*\}\}": "{{ copied() ? t.copiedShort : t.copyLinkShort }}",
    r"\{\{\s*isPl\s*\?\s*'Otwórz stronę wtyczki'\s*:\s*'Open Web Store'\s*\}\}": "{{ t.openStore }}",
    r"\{\{\s*isPl\s*\?\s*'Włącz wtyczkę z menu Kiwi \(3 kropki\)'\s*:\s*'Open Extension from the 3-Dots Menu'\s*\}\}": "{{ t.step3Title }}",
    r"\{\{\s*isPl\s*\?\s*'Krok 3'\s*:\s*'Step 3'\s*\}\}": "{{ t.step3 }}",
    r"\{\{\s*isPl[\s\r\n]*\? 'Kliknij menu w prawym górnym rogu Kiwi \(trzy kropki ⋮\), zjedź na sam dół listy i stuknij QuizSolver\. Zaloguj się tym samym adresem e-mail, aby mieć dostęp do swoich kredytów\.'[\s\r\n]*:\s*'Tap the three dots \(⋮\) in the top-right corner of Kiwi and scroll to the bottom\. Tap QuizSolver and log in with your email to access your credits\.'\s*\}\}": "{{ t.step3Desc }}",
    r"\{\{\s*mockMenuCopy\.newTab\s*\}\}": "{{ t.newTab }}",
    r"\{\{\s*mockMenuCopy\.settings\s*\}\}": "{{ t.settings }}",
    r"\{\{\s*mockMenuCopy\.title\s*\}\}": "{{ t.qsTitle }}",
    r"\{\{\s*mockMenuCopy\.active\s*\}\}": "{{ t.active }}",
    r"\{\{\s*isPl\s*\?\s*'Rozwiązuj testy bezpośrednio na telefonie'\s*:\s*'Solve Quizzes Directly on Mobile'\s*\}\}": "{{ t.step4Title }}",
    r"\{\{\s*isPl\s*\?\s*'Gotowe'\s*:\s*'Ready'\s*\}\}": "{{ t.step4 }}",
    r"\{\{\s*isPl[\s\r\n]*\? 'Otwórz dowolny test w Kiwi\. Otwórz menu Kiwi -> QuizSolver -> kliknij „Rozwiąż obecną stronę\" lub użyj FocusScan\.'[\s\r\n]*:\s*'Open any quiz in Kiwi\. Open Kiwi menu -> QuizSolver -> tap \"Solve current page\" or use FocusScan\.'\s*\}\}": "{{ t.step4Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Wszystko działa dokładnie tak jak na komputerze'\s*:\s*'Works exactly like the desktop version'\s*\}\}": "{{ t.worksSame }}",
    r"\{\{\s*isPl\s*\?\s*'Wykrywanie pytań, tryb podpowiedzi, FocusScan i historia pytań są w 100% dostępne\.'\s*:\s*'Automatic detection, hint mode, FocusScan and study history are fully supported\.'\s*\}\}": "{{ t.worksSameDesc }}",
    r"\{\{\s*isPl\s*\?\s*'Przetestuj na darmowym Demo'\s*:\s*'Try Free Demo'\s*\}\}": "{{ t.tryDemo }}",
    r"\{\{\s*isPl\s*\?\s*'Auto-wykrywanie pytań'\s*:\s*'Auto question detection'\s*\}\}": "{{ t.feat1Title }}",
    r"\{\{\s*isPl\s*\?\s*'Wtyczka sama znajduje pytania na stronie'\s*:\s*'Finds quiz questions on the page automatically'\s*\}\}": "{{ t.feat1Desc }}",
    r"\{\{\s*isPl\s*\?\s*'FocusScan'\s*:\s*'FocusScan'\s*\}\}": "{{ t.feat2Title }}",
    r"\{\{\s*isPl\s*\?\s*'Skanuj i rozwiązuj wybrany fragment ekranu'\s*:\s*'Scan and solve a selected part of the screen'\s*\}\}": "{{ t.feat2Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Tryb podpowiedzi'\s*:\s*'Hint mode'\s*\}\}": "{{ t.feat3Title }}",
    r"\{\{\s*isPl\s*\?\s*'Wskazówki zamiast gotowych odpowiedzi'\s*:\s*'Gentle nudges instead of full answers'\s*\}\}": "{{ t.feat3Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Historia pytań'\s*:\s*'Question history'\s*\}\}": "{{ t.feat4Title }}",
    r"\{\{\s*isPl\s*\?\s*'Wszystko zapisane do nauki przed egzaminem'\s*:\s*'Everything saved for exam revision'\s*\}\}": "{{ t.feat4Desc }}",
    r"\{\{\s*isPl\s*\?\s*'Wideo Poradnik dla iOS \(iPhone / iPad\)'\s*:\s*'Video Tutorial for iOS \(iPhone / iPad\)'\s*\}\}": "{{ t.iosTitle }}",
    r"\{\{\s*isPl\s*\?\s*'Zobacz 40-sekundowe nagranie pokazujące instalację rozszerzenia na urządzeniach Apple\.'\s*:\s*'Watch this 40-second video demonstrating the setup process on Apple devices\.'\s*\}\}": "{{ t.iosDesc }}",
    r"\{\{\s*isPl\s*\?\s*'Otwórz na YouTube'\s*:\s*'Open in YouTube app'\s*\}\}": "{{ t.iosBtn }}"
}

for old, new in replacements.items():
    content = re.sub(old, new, content, flags=re.MULTILINE)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print('Success')
