import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./pages/home.component').then(m => m.HomeComponent), data: { locale: 'en' } },
  { path: 'pl', loadComponent: () => import('./pages/home.component').then(m => m.HomeComponent), data: { locale: 'pl' } },
  { path: 'dashboard', loadComponent: () => import('./pages/dashboard.component').then(m => m.DashboardComponent), data: { locale: 'en' } },
  { path: 'admin', loadComponent: () => import('./pages/admin.component').then(m => m.AdminComponent) },
  { path: 'pl/dashboard', loadComponent: () => import('./pages/dashboard.component').then(m => m.DashboardComponent), data: { locale: 'pl' } },
  { path: 'quiz', loadComponent: () => import('./pages/quiz.component').then(m => m.QuizComponent), data: { locale: 'en' } },
  { path: 'pl/quiz', loadComponent: () => import('./pages/quiz.component').then(m => m.QuizComponent), data: { locale: 'pl' } },
  { path: 'privacy', loadComponent: () => import('./pages/privacy.component').then(m => m.PrivacyComponent), data: { locale: 'en' } },
  { path: 'pl/privacy', loadComponent: () => import('./pages/privacy.component').then(m => m.PrivacyComponent), data: { locale: 'pl' } },
  { path: 'success', loadComponent: () => import('./pages/status-pages.component').then(m => m.StatusPageComponent), data: { locale: 'en', pageKey: 'success' } },
  { path: 'pl/success', loadComponent: () => import('./pages/status-pages.component').then(m => m.StatusPageComponent), data: { locale: 'pl', pageKey: 'success' } },
  { path: '404', loadComponent: () => import('./pages/status-pages.component').then(m => m.StatusPageComponent), data: { locale: 'en', pageKey: 'notFound' } },
  { path: 'pl/404', loadComponent: () => import('./pages/status-pages.component').then(m => m.StatusPageComponent), data: { locale: 'pl', pageKey: 'notFound' } },
  { path: 'quiz-solver-ai', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'quizSolverAi' } },
  { path: 'pl/quiz-solver-ai', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'quizSolverAi' } },
  { path: 'testportal-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'testportal' } },
  { path: 'pl/testportal-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'testportal' } },
  { path: 'moodle-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'moodle' } },
  { path: 'pl/moodle-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'moodle' } },
  { path: 'canvas-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'canvas' } },
  { path: 'pl/canvas-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'canvas' } },
  { path: 'google-forms-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'googleForms' } },
  { path: 'pl/google-forms-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'googleForms' } },
  { path: 'microsoft-forms-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'microsoftForms' } },
  { path: 'pl/microsoft-forms-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'microsoftForms' } },
  { path: 'blackboard-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'blackboard' } },
  { path: 'pl/blackboard-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'blackboard' } },
  { path: 'quizlet-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'quizlet' } },
  { path: 'pl/quizlet-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'quizlet' } },
  { path: 'socrative-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'socrative' } },
  { path: 'pl/socrative-quiz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'socrative' } },
  { path: 'kahoot-ai-bot', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'kahoot' } },
  { path: 'pl/kahoot-ai-bot', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'kahoot' } },
  { path: 'quizizz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'en', pageKey: 'quizizz' } },
  { path: 'pl/quizizz-solver', loadComponent: () => import('./pages/platform.component').then(m => m.PlatformComponent), data: { locale: 'pl', pageKey: 'quizizz' } },
  { path: '**', loadComponent: () => import('./pages/status-pages.component').then(m => m.StatusPageComponent), data: { locale: 'en', pageKey: 'notFound' } }
];
